---
extends: "default"
rules:
  comments: "enable"
  empty-values: "disable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
ignore: |
  .venv/
  {{ cookiecutter.project_slug }}/development/docker-compose.base.yml
  {{ cookiecutter.project_slug }}/invoke.example.yml
